project:
  type: book
  output-dir: docs
  resources:
    - maps

book:
  title: Making Indiana University
  subtitle: History, Landscape, and a Sense of Place
  author: 
    name: James H. Capshew
    corresponding: true
    affiliations: 
      - name: |- 
          Department of History and Philosophy of Science and Medicine
          
          Indiana University Bloomington 
        department: History and Philosophy of Science and Medicine
        address: Ballantine Hall 920
        city: Bloomington
        state: IN
        country: USA
        postal-code: 47405
        url: https://hpsc.indiana.edu/index.html
        ror: https://ror.org/02k40bc56
    email: jcapshew@indiana.edu 
    url: https://hpsc.indiana.edu/about/emeriti-faculty/capshew-james.html
    orcid: 0009-0009-3238-9464
    degrees: 
      - Ph.D.
  date: last-modified
  date-format: "YYYY"
  abstract: |
    This book sheds light on the creation of Indiana University's institutional identity and image over its two centuries of existence by investigating the role of historians, archivists, and others in documenting its historical record. As such, it is an exercise in historiography, or the study of the history of IU history. The first part presents a rationale for an inclusive view of contributors to IU history, including not only historians and archivists but also architects, groundskeepers, and other members of its academic community. Essays on the contributions of the first professor as well as the invention of the genre of Indiana University history provides a useful provenance. The second section supplies a chronological study of the history of IU's distinctive campus design, from its beginning in 1885 to 2020, to illustrate the essential role that place plays in university culture. The third and final part are essays that uncover hidden efforts to sustain the university's historical record in publications, faculty memorials, and historic preservation. By its interrogation of the sources and methods that construct the historical record, this book makes a unique contribution to the study of Indiana University history and culture.  
  description: |
    Essays exploring institutional culture, campus design, and sense of place at Indiana University Bloomington. 
  references: references.bib
  cover-image: images/cover1-4.png
  cover-image-alt: Front cover of book with title, subtitle, and author surrounding a drawing of the Rose Well House, constructed in 1908 and named for its benefactor, Theodore Rose, class of 1875. Located in Dunn's Woods near Owen Hall and Wylie Hall. 
  downloads: [pdf, epub]
  doi: 10.5967/m1tv-xc36
  language: "en-US"
  license: "CC BY-NC-ND 4.0"
  type: book
  publisher: "Indiana University Bloomington Libraries Publishing"
  publisher-place: Bloomington, IN
  favicon: images/cover1-4.png
  site-url: https://iulibscholcomm.github.io/making-IU/
  repo-url: https://github.com/IULibScholComm/making-IU
  issue-url: https://github.com/IULibScholComm/making-IU/issues
  repo-actions: [source, issue]
  reader-mode: true
  google-analytics: "G-SFJKVCT3LT"
  search: 
    location: sidebar
    type: textbox
    copy-button: true
    show-item-context: true
  page-navigation: true
  back-to-top-navigation: true
  image: images/cover1-4.png
  image-alt: A drawing of the Rose Well House, constructed in 1908 and named for its benefactor, Theodore Rose, class of 1875. Located in Dunn's Woods near Owen Hall and Wylie Hall. 
  bread-crumbs: true
  twitter-card: true
  open-graph: true
  sidebar: 
    aria-label: Table of Contents
    style: docked
    collapse-level: 1
    pinned: true
    logo: images/cover1-4.png
    logo-alt: A drawing of the Rose Well House, constructed in 1908 and named for its benefactor, Theodore Rose, class of 1875. Located in Dunn's Woods near Owen Hall and Wylie Hall. 

  chapters:
    - index.qmd
    - dedication.qmd
    - intro.qmd
    - part1.qmd
    - one.qmd
    - two.qmd
    - three.qmd
    - part2.qmd
    - four.qmd
    - five.qmd
    - six.qmd
    - seven.qmd
    - part3.qmd
    - eight.qmd
    - nine.qmd
    - ten.qmd
    - partcoda.qmd
    - coda.qmd
    - imap.qmd
    - acknowledgments.qmd
    - references.qmd

google-scholar: true
csl: chicago-fullnote-bibliography-note-visible-footnote-too.csl
citations-hover: true
bibliography: references.bib
nocite: |
  @*

profile:
  group:
    - [digital, physical]